apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acstest
  namespace: demo1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
