apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo1
    repoURL: https://github.com/RedHatNordicsSA/advanced_deployment_demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true