apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-namespace-demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: mbatest5
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlay/namespace
    repoURL: https://github.com/RedHatNordicsSA/advanced_deployment_demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true