apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-http-example
    app.kubernetes.io/component: rest-http-example
    app.kubernetes.io/instance: rest-http-example
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: rest-http-example-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-ubi8
  name: rest-http-example
  namespace: demo4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rest-http-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-http-example
        deploymentconfig: rest-http-example
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/demo4/rest-http-example
        imagePullPolicy: Always
        name: rest-http-example
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
