apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../deployment/base
patchesStrategicMerge:
- route.yaml
namePrefix: qa-
namespace: qa
commonLabels:
  environment: qa
  sre-team: qa-team
images:
- name: image-registry.openshift-image-registry.svc:5000/demo4/rest-http-example
  newName: image-registry.openshift-image-registry.svc:5000/qa/qa-rest-http-example
  newTag: latest
replicas:
- name: rest-http-example
  count: 2
patchesJson6902:
- target:
    version: v1
    kind: BuildConfig
    name: qa-rest-http-example
  patch: |-
    - op: replace
      path: /spec/output/to/name
      value: "qa-rest-http-example:latest"