apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../deployment/base
- ../../build/base
patchesStrategicMerge:
- route.yaml
namePrefix: dev-
namespace: dev
commonLabels:
  environment: development
  sre-team: dev-team
images:
- name: image-registry.openshift-image-registry.svc:5000/demo4/rest-http-example
  newName: image-registry.openshift-image-registry.svc:5000/dev/dev-rest-http-example
  newTag: latest
replicas:
- name: rest-http-example
  count: 1
patchesJson6902:
- target:
    version: v1
    kind: BuildConfig
    name: dev-rest-http-example
  patch: |-
    - op: replace
      path: /spec/output/to/name
      value: "dev-rest-http-example:latest"