apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: integration-test
  namespace: demo3
spec:
  steps:
    - command:
        - /bin/bash
        - '-c'
        - sleep 18
      image: registry.redhat.io/ubi7/ubi-minimal
      name: maven-integration-tests
      resources: {}
